### ISSUE TITLE
Implement broadcasting of producers

### ISSUE THREAD

**Issue by eskarpnes** [eskarpnes/PySSMic#34]
- When a consumer is made he should have a list of every producer.
- If a new producer is made it should be broadcasted to every consumer

**Comment by maalfrid** [comment]
It seems like this i actually already implemented :D 

_When a consumer is made he should have a list of every producer_ is implemented in ```new_job``` (in ```manager.py```)

_If a new producer is made it should be broadcasted to every consumer_ is implemented in ```register_producer``` (in ```manager.py```)
